FROM python:3.11-slim

WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy app files
COPY docs_v01.json app_v01.py search_v01.py ./

# Set PORT
ENV PORT=8000

# Start app
EXPOSE ${PORT}
CMD ["python", "app_v01.py"]
